# Generated by Django 4.1.1 on 2022-09-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='dog',
            name='collars',
            field=models.ManyToManyField(to='dogs.collar'),
        ),
    ]
